- name: 'Install {{ item.name }} repository key'
  ansible.builtin.get_url:
    url: '{{ item.key_url }}'
    dest: '/usr/share/keyrings/{{ item.name }}.{{ item.key_format }}'
    mode: '0644'
    force: true # replace if the content changes
  when: "item.state == 'present'"
  become: true

- name: 'Uninstall {{ item.name }} repository key' # noqa: risky-file-permissions (only delete files)
  ansible.builtin.file:
    path: '/etc/apt/trusted.gpg.d/{{ item.name }}.{{ item.key_format }}'
    state: '{{ item.state }}'
  when: "item.state == 'absent'"
  become: true

- name: "{{ (item.state == 'present') | ternary('Install', 'Uninstall') }} {{ item.name }} repository"
  ansible.builtin.apt_repository:
    filename: '{{ item.name }}'
    repo: '{{ item.repo }}'
    state: '{{ item.state }}'
    update_cache: false
  become: true
  notify:
    - 'Update package indexes'
