---

- name: 'Install base packages'
  ansible.builtin.package:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'needrestart'
      - 'python3-apt'
    state: 'present'
  become: true

- name: 'Remove unneeded default APT configurations'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/apt/apt.conf'
    - '/etc/apt/apt.conf.d/00CDMountPoint'
    - '/etc/apt/apt.conf.d/00trustcdrom'
    - '/etc/apt/apt.conf.d/02proxy'
    - '/etc/apt/apt.conf.d/10periodic'
    - '/etc/apt/apt.conf.d/20archive'
    - '/etc/apt/apt.conf.d/20listchanges'
  become: true

- name: 'Copy configuration files and scripts'
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/apt/apt.conf.d/00aptitude'
    - 'etc/apt/apt.conf.d/00InstallRecommends'
    - 'etc/apt/sources.list'
    - 'etc/dpkg/dpkg.cfg'
  notify:
    - 'Update package indexes'
  become: true
