---
- name: 'Install base packages'
  ansible.builtin.package:
    name:
      - 'apt-listchanges'
      - 'apt-show-versions'
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'needrestart'
      - 'python3-apt'
      - 'unattended-upgrades'
    state: 'present'
  become: true

- name: 'Remove unneeded default APT configurations'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/apt/apt.conf'
    - '/etc/apt/apt.conf.d/00CDMountPoint'
    - '/etc/apt/apt.conf.d/00trustcdrom'
    - '/etc/apt/listchanges.conf.d'
  become: true

- name: 'Copy configuration files and scripts'
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/apt/sources.list'
    - 'etc/apt/listchanges.conf'
    - 'etc/apt/apt.conf.d/00aptitude'
    - 'etc/apt/apt.conf.d/01autoremove'
    - 'etc/apt/apt.conf.d/20auto-upgrades'
    - 'etc/apt/apt.conf.d/20listchanges'
    - 'etc/apt/apt.conf.d/50unattended-upgrades'
    - 'etc/apt/apt.conf.d/70debconf'
    - 'etc/dpkg/dpkg.cfg'
  notify:
    - 'Update package indexes'
  become: true

- name: 'Configure extra repositories'
  ansible.builtin.include_tasks: 'extra_repositories.yml'
  loop: '{{ apt__extra_repositories }}'

# Required because package indexes must be updated before the packages role
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
