---
- name: 'Install firewalld'
  ansible.builtin.package:
    name: 'firewalld'
    state: 'present'
  become: true

- name: 'Set up sources'
  ansible.posix.firewalld:
    zone: '{{ item.zone }}'
    source: '{{ item.source }}'
    permanent: '{{ item.permanent | bool }}'
    immediate: '{{ item.immediate | bool }}'
    state: '{{ item.state }}'
  loop: '{{ firewalld__sources }}'
  become: true


- name: 'Set up services'
  ansible.posix.firewalld:
    zone: '{{ item.zone }}'
    service: '{{ item.service }}'
    permanent: '{{ item.permanent | bool }}'
    immediate: '{{ item.immediate | bool }}'
    state: '{{ item.state }}'
  loop: '{{ firewalld__services }}'
  become: true
