---
# Whether Apache must be installed (`present`) or not (`absent`).
apache_server__state: 'absent'

# IP addresses apache must bind to.
apache_server__bindings:
  - name: 'localhost'
    ip: '127.0.0.1'
    ports: [80]

# File descriptor limit.
apache_server__ulimit_max_files: 65536

# Arguments to the web server when it starts.
apache_server__arguments: ''

# mpm_event_module configuration.
# See https://httpd.apache.org/docs/2.4/mod/event.html.
apache_server__mpm_event_start_servers: 2
apache_server__mpm_event_min_spare_threads: 25
apache_server__mpm_event_max_spare_threads: 75
apache_server__mpm_event_thread_limit: 64
apache_server__mpm_event_threads_per_child: 25
apache_server__mpm_event_max_request_workers: 150
apache_server__mpm_event_max_connections_per_child: 0
