---
- name: 'Server playbook'
  hosts: 'servers'
  roles:
    - role: 'marcwrobel.debian_basics.bootstrap'
      tags: ['bootstrap']
    - role: 'marcwrobel.debian_basics.etckeeper'
      tags: ['etckeeper']
    - role: 'marcwrobel.debian_basics.sysctl'
      tags: ['sysctl']
    - role: 'marcwrobel.debian_basics.root'
      tags: ['root', 'user']
    - role: 'marcwrobel.debian_basics.apt'
      tags: ['apt']
    - role: 'marcwrobel.debian_basics.packages'
      tags: ['packages']
    - role: 'marcwrobel.debian_basics.banner'
      tags: ['banner']
    - role: 'marcwrobel.debian_basics.sudo'
      tags: ['sudo']
    - role: 'marcwrobel.debian_basics.git'
      tags: ['packages', 'git']
    - role: 'marcwrobel.debian_basics.vim'
      tags: ['packages', 'vim']
    - role: 'marcwrobel.debian_basics.network'
      tags: ['net', 'network']
    - role: 'marcwrobel.debian_basics.firewalld'
      tags: ['fw', 'firewall', 'firewalld']
    - role: 'marcwrobel.debian_server.apache_server'
      tags: ['apache']
    - role: 'marcwrobel.debian_basics.certbot'
      tags: ['certbot', 'ssl']
