---

- name: 'Servers playbook'
  hosts: 'servers'
  collections:
    - 'marcwrobel.debian_basics'
  tasks:
    - name: 'Display all variables/facts'
      debug:
        var: 'hostvars[inventory_hostname]'
