---

- name: Install repository key
  ansible.builtin.apt_key:
    id: '{{ virtualbox__gpg_key_id }}'
    url: '{{ virtualbox__gpg_key_url }}'
    state: '{{ virtualbox__state }}'

- name: Install repository
  ansible.builtin.apt_repository:
    filename: 'vscodium'
    repo: '{{ virtualbox__repo }}'
    state: '{{ virtualbox__state }}'
    update_cache: true

- name: Install packages
  ansible.builtin.package:
    name: '{{ virtualbox__package_base }}{{ virtualbox__version }}'
    state: '{{ virtualbox__state }}'
  ignore_errors: '{{ ansible_check_mode }}'
