---

- name: Install
  ansible.builtin.package:
    name: '{{ postfix_satellite__packages }}'
    state: 'present'
  become: true

- name: Remove unnecessary files
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/postfix/dynamicmaps.cf.d'
    - '/etc/postfix/main.cf.proto'
    - '/etc/postfix/master.cf.proto'
    - '/etc/postfix/postfix-files.d'
    - '/etc/postfix/sasl'
  become: true

- name: Configure
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/aliases'
    - 'etc/mailname'
    - 'etc/postfix/dynamicmaps.cf'
    - 'etc/postfix/main.cf'
    - 'etc/postfix/master.cf'
  become: true
  notify: 'Restart postfix'

- name: Manage lookup tables
  block:
    - name: Configure lookup tables
      ansible.builtin.template:
        src: 'etc/postfix/{{ item }}.j2'
        dest: '/etc/postfix/{{ item }}'
        owner: 'root'
        group: 'root'
        mode: '0600'
      loop: ['sasl_passwd', 'generic']
      become: true
      register: 'lookup_tables'

    - name: Regenerate lookup tables # noqa no-changed-when run only when lookup_tables is changed
      ansible.builtin.command: 'postmap /etc/postfix/{{ item }}'
      loop: ['sasl_passwd', 'generic']
      when: 'lookup_tables is changed'
      become: true
      notify: 'Restart postfix'

    - name: Set permission on lookup tables
      ansible.builtin.file:
        path: '/etc/postfix/{{ item }}.db'
        owner: 'root'
        group: 'root'
        mode: '0600'
      loop: ['sasl_passwd', 'generic']
      become: true
      ignore_errors: '{{ ansible_check_mode }}' # file may not exist if launched first in check mode

- name: Activate service
  ansible.builtin.service:
    name: 'postfix'
    enabled: true
    state: 'started'
  become: true
