---
- name: Install repository key
  ansible.builtin.apt_key:
    id: '{{ nodejs__gpg_key_id }}'
    url: '{{ nodejs__gpg_key_url }}'
    state: '{{ nodejs__state }}'

- name: Install repository
  ansible.builtin.apt_repository:
    filename: 'nodejs'
    repo: 'deb {{ nodejs__repo_url }}/node_{{ nodejs__version }}.x {{ ansible_distribution_release }} main'
    state: '{{ nodejs__state }}'
    update_cache: true

- name: Install packages
  ansible.builtin.package:
    name: '{{ nodejs__packages }}'
    state: '{{ nodejs__state }}'
  ignore_errors: '{{ ansible_check_mode }}'
