---
namespace: marcwrobel
name: debian_desktop
description: A collection of roles for Debian on a Desktop.
version: 1.0.0
license: ['MIT']

readme: README.md
authors: ['Marc Wrobel (https://www.marcwrobel.fr/)']

dependencies: {}

tags: ['linux', 'debian', 'desktop']

repository: https://github.com/marcwrobel/debian-playbooks
documentation: https://github.com/marcwrobel/debian-playbooks
homepage: https://github.com/marcwrobel/debian-playbooks
issues: https://github.com/marcwrobel/debian-playbooks/issues
