---
- name: Install sudo
  ansible.builtin.package:
    name: 'sudo'
    state: 'present'
  become: true

- name: Ensure sudoers.d directory exists
  ansible.builtin.file:
    path: '/etc/sudoers.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'
  become: true

- name: Copy global configuration
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0440'
  loop:
    - 'etc/sudoers'
  become: true
