---

- name: Install
  ansible.builtin.package:
    name: '{{ apache_server__packages }}'
    state: 'present'
  become: true

- name: Remove unnecessary files
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/apache2/conf-available'
    - '/etc/apache2/conf-enabled'
    - '/etc/apache2/mods-available'
    - '/etc/apache2/mods-enabled'
  become: true

- name: Configure
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop:
    - 'etc/apache2/apache2.conf'
    - 'etc/apache2/default_access.conf'
    - 'etc/apache2/envvars'
    - 'etc/apache2/headers.conf'
    - 'etc/apache2/http2.conf'
    - 'etc/apache2/logging.conf'
    - 'etc/apache2/mime.conf'
    - 'etc/apache2/mpm_event.conf'
    - 'etc/apache2/optional_modules.conf'
    - 'etc/apache2/ports.conf'
    - 'etc/apache2/ssl.conf'
  become: true
  notify: 'Restart apache'

- name: Configure default page
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'www-data'
    group: 'www-data'
    mode: '0644'
  loop:
    - 'var/www/html/index.html'
  become: true

- name: Configure default VirtualHosts
  ansible.builtin.template:
    src: 'etc/apache2/sites-available/{{ item }}.j2'
    dest: '/etc/apache2/sites-available/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop:
    - '000-default.conf'
    - 'default-ssl.conf'
  become: true
  notify: 'Reload apache'

- name: Activate default VirtualHosts
  ansible.builtin.file:
    src: '/etc/apache2/sites-available/{{ item }}'
    dest: '/etc/apache2/sites-enabled/{{ item }}'
    owner: 'root'
    group: 'root'
    state: 'link'
  loop:
    - '000-default.conf'
    - 'default-ssl.conf'
  become: true
  notify: 'Reload apache'
