---
- name: Install packages
  ansible.builtin.package:
    name: '{{ flatpak__packages }}'
    state: 'present'
  become: true

- name: Add flatpak remotes to the system installation
  community.general.flatpak_remote:
    name: '{{ flatpak__remote.name }}'
    state: present
    flatpakrepo_url: '{{ flatpak__remote.url }}'
  loop: '{{ flatpak__system_remotes }}'
  loop_control:
    loop_var: 'flatpak__remote'
  ignore_errors: '{{ ansible_check_mode }}'
