---
- name: Register remotes
  community.general.flatpak_remote:
    name: '{{ flatpak__remote.name }}'
    flatpakrepo_url: '{{ flatpak__remote.url }}'
    state: present
  loop: '{{ flatpak__remotes }}'
  loop_control:
    loop_var: 'flatpak__remote'

- name: Install packages
  community.general.flatpak:
    name: '{{ flatpak__app }}'
    state: 'present'
    method: 'user'
  loop: '{{ flatpak__apps }}'
  loop_control:
    loop_var: 'flatpak__app'
