---
# Default packages to uninstall, along with variables for adding packages for an host or an hosts group.
packages__default_blacklist:
  - "telnet" # use netcat instead
  - "manpages-de" # only english manpages are needed
  - "manpages-es" # only english manpages are needed
  - "manpages-fr" # only english manpages are needed
  - "manpages-it" # only english manpages are needed
  - "manpages-pl" # only english manpages are needed
  - "manpages-pt" # only english manpages are needed
packages__group_blacklist: []
packages__host_blacklist: []
packages__blacklist: "{{ packages__default_blacklist + packages__group_blacklist + packages__host_blacklist }}"

# Default packages to install, along with variables for adding packages for an host or an hosts group.
packages__default_list:
  # Clients
  - "curl" # command line tool for transferring data with URL syntax
  - "httpie" # cURL-like tool for humans
  - "lftp" # sophisticated command-line FTP/HTTP/BitTorrent client programs
  - "rsync" # fast, versatile, remote (and local) file-copying tool
  # Compression
  - "atool" # tool for managing file archives of various types
  - "bzip2" # high-quality block-sorting file compressor
  - "p7zip" # 7zr file archiver with high compression ratio
  - "unzip" # de-archiver for .zip files
  - "xz-utils" # XZ-format compression utilities
  - "zip" # archiver for .zip files
  - "zstd" # fast lossless compression algorithm -- CLI tool
  # Editors
  - 'vim'
  # System
  - "netcat-openbsd" # TCP/IP swiss army knife
  - "util-linux" # miscellaneous system utilities
  - "uptimed" # daemon to track uptimes, especially the high ones
  # Misc
  - "gnupg" # GNU privacy guard - a free PGP replacement
  - "jq" # lightweight and flexible command-line JSON processor
  - "uuid" # Universally Unique Identifier Command-Line Tool
packages__group_list: []
packages__host_list: []
packages__list: "{{ packages__default_list + packages__group_list + packages__host_list }}"
