---

- name: Uninstall blacklisted packages
  ansible.builtin.package:
    name: '{{ packages__blacklist }}'
    state: 'absent'
  become: true

- name: Install packages
  ansible.builtin.package:
    name: '{{ packages__list }}'
    state: 'present'
  become: true
