---

# apticron is a shell script which generates a mail with a list of all packages currently pending an upgrade, as well as summary of changes - using
# apt-listchanges - to a configurable Email address.

- name: 'Install Apticron'
  package:
    name:
      - 'apt-listchanges'
      - 'apticron-systemd'
    state: 'present'
  become: true

- name: 'Configure Apticron '
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/apt/listchanges.conf'
    - 'etc/apticron/apticron.conf'
  become: true

- name: 'Enable Apticron'
  ansible.builtin.systemd:
    name: 'apticron.timer'
    state: 'started'
    enabled: true
    daemon_reload: true
  become: true
