---

# cloud-init does not setup IPv6 and configure IPv4 using DHCP
- name: 'Uninstall cloud-init'
  package:
    name: 'cloud-init'
    state: 'absent'
  become: true

# configuration resides only in /etc/network/interfaces
- name: 'Remove /etc/network/interfaces.d'
  file:
    path: '/etc/network/interfaces.d'
    state: 'absent'
  become: true

# IPv6 auto-configuration cause issues on Kimsufi server
- name: 'Disable IPv6 auto-configuration'
  sysctl:
    name: 'net.ipv6.conf.all.autoconf'
    value: '0'
    state: 'present'
  loop:
    - 'net.ipv6.conf.all.autoconf'
    - 'net.ipv6.conf.all.accept_ra'
  become: true

- name: 'Configure /etc/network/interfaces'
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'etc/network/interfaces'
  become: true
