---
- name: Install packages
  ansible.builtin.package:
    name: "{{ git__packages }}"
    state: "present"
  become: true

- name: Copy system configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - "etc/gitconfig"
  become: true
