galaxy_info:
  author: 'Marc Wrobel'
  description: 'Configures a legal banner'
  license: 'MIT'
  min_ansible_version: '6.0.0'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
  galaxy_tags: ['linux', 'debian', 'banner', 'legal']
dependencies: []
