---

apt__extra_repositories:
  - name: 'vscodium'
    key_url: 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg'
    key_format: 'asc'
    repo: 'deb [ signed-by=/usr/share/keyrings/vscodium.asc ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main'
    state: 'present'
  - name: 'node_16.x'
    key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    key_format: 'asc'
    repo: "deb [signed-by=/usr/share/keyrings/node_16.x.asc ] https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    state: 'present'
  - name: 'virtualbox'
    key_url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    key_format: 'asc'
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/virtualbox.asc] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: 'present'

# Description from https://pkgs.org
packages__host_list:
  # Clients
  - 'curl' # command line tool for transferring data with URL syntax
  - 'httpie' # cURL-like tool for humans
  - 'lftp' # sophisticated command-line FTP/HTTP/BitTorrent client programs
  # Compression
  - 'atool' # tool for managing file archives of various types
  - 'p7zip' # 7zr file archiver with high compression ratio
  - 'xz-utils' # XZ-format compression utilities
  # Desktop
  - 'chromium' # The open-source version of Chrome
  - 'fonts-liberation' # A replacement for Times New Roman, Arial and Courier New
  - 'gthumb' # image viewer and browser
  - 'meld' # graphical tool to diff and merge files
  # Development
  - 'build-essential' # Required by asdf, nodejs
  - 'git' # fast, scalable, distributed revision control system
  - 'gitg' # git repository viewer
  - 'hexedit' # viewer and editor in hexadecimal or ASCII for files or devices
  - 'libssl-dev' # needed while installing ruby using asdf
  - 'openjdk-17-doc' # OpenJDK Development Kit (JDK) documentation
  - 'openjdk-17-jdk' # OpenJDK Development Kit (JDK)
  - 'openjdk-17-source' # OpenJDK Development Kit (JDK) source files
  - 'pipenv' # creates and manages a virtualenv for your projects
  # Editors
  - 'geany' # fast and lightweight IDE
  - 'geany-plugins' # set of plugins for Geany
  - 'geany-plugin-extrasel' # extra selection plugin for Geany
  # System
  - 'htop' # Interactive process viewer
  - 'ncdu' # ncurses disk usage viewer
  - 'netcat-openbsd' # TCP/IP swiss army knife
  - 'nmon' # performance monitoring tool for Linux
  # Security
  - 'torbrowser-launcher' # helps download and run the Tor Browser Bundle
  # Misc
  - 'dos2unix' # convert text file line endings between CRLF and LF
  - 'gnupg' # GNU privacy guard - a free PGP replacement
  - 'jc' # JSON CLI output utility
  - 'jq' # lightweight and flexible command-line JSON processor
  - 'pass' # lightweight directory-based password manager
  - 'uuid' # Universally Unique Identifier Command-Line Tool
  - 'renrot' # rename and rotate files according to EXIF tags
  # Packages from external repositories
  - 'codium' # from vscodium
  - 'nodejs' # from node_NN.x
  - 'virtualbox-7.0' # from virtualbox

asdf__plugins:
  - name: 'ruby'
  - name: 'nodejs'
  - name: 'java'
  - name: 'maven'
  - name: 'quarkus'

dotfiles__repository: 'https://github.com/marcwrobel/dotfiles.git'
