---
packages__host_list:
  # Clients
  - 'curl' # command line tool for transferring data with URL syntax
  - 'httpie' # cURL-like tool for humans
  - 'lftp' # sophisticated command-line FTP/HTTP/BitTorrent client programs
  # Compression
  - 'atool' # tool for managing file archives of various types
  - 'p7zip' # 7zr file archiver with high compression ratio
  - 'xz-utils' # XZ-format compression utilities
  # Desktop
  - 'chromium' # The open-source version of Chrome
  - 'flatpak' # Application deployment framework for desktop apps
  - 'fonts-liberation' # A replacement for Times New Roman, Arial and Courier New
  - 'gnome-software-plugin-flatpak' # Flatpak support for GNOME Software
  - 'gthumb' # image viewer and browser
  - 'renrot' # rename and rotate files according to EXIF tags
  # Development
  - 'build-essential' # Required by asdf
  - 'git' # fast, scalable, distributed revision control system
  - 'gitg' # git repository viewer
  - 'libssl-dev' # needed while installing ruby using asdf
  - 'openjdk-17-doc' # OpenJDK Development Kit (JDK) documentation
  - 'openjdk-17-jdk' # OpenJDK Development Kit (JDK)
  - 'openjdk-17-source' # OpenJDK Development Kit (JDK) source files
  - 'pipenv' # creates and manages a virtualenv for your projects
  # Editors
  - 'geany' # fast and lightweight IDE
  - 'geany-plugins' # set of plugins for Geany
  - 'geany-plugin-extrasel' # extra selection plugin for Geany
  # System
  - 'htop' # Interactive process viewer
  - 'netcat-openbsd' # TCP/IP swiss army knife
  # Security
  - 'torbrowser-launcher' # helps download and run the Tor Browser Bundle
  # Misc
  - 'gnupg' # GNU privacy guard - a free PGP replacement
  - 'jq' # lightweight and flexible command-line JSON processor
  - 'pass' # lightweight directory-based password manager
  - 'uuid' # Universally Unique Identifier Command-Line Tool
  - 'stow' # A symlink farm manager

flatpak__apps:
  - 'com.jetbrains.IntelliJ-IDEA-Community' # an IDE written in Java for developing computer software
  - 'com.slack.Slack' # a messaging program designed specifically for the workplace
  - 'com.vscodium.codium' # open source software binaries of VS Code, a source-code editor

asdf__plugins:
  - name: 'ruby'
  - name: 'nodejs'
  - name: 'java'
  - name: 'maven'
  - name: 'quarkus'
    repository: 'https://github.com/marcwrobel/asdf-quarkus'

dotfiles__repository: 'https://github.com/marcwrobel/dotfiles.git'
