---
root_email: admin@marcwrobel.fr

packages__host_list:
  - 'htop' # Interactive process viewer
packages__host_blacklist:
  - 'cloud-init' # cloud-init does not setup IPv6 and configure IPv4 using DHCP

network__interface: 'eno0'
network__ipv4_address: '5.196.89.31'
network__ipv4_gateway: '5.196.95.254'
network__ipv6_address: '2001:41d0:a:fc1f::1'
network__ipv6_gateway: '2001:41d0:a:fcff:ff:ff:ff:ff'

sysctl__hosts_additional_variables:
  - net.ipv6.conf.all.autoconf:
      description: >-
        IPv6 auto-configuration is causing issues on Kimsufi server.
        See https://docs.ovh.com/fr/dedicated/network-ipv6/.
      value: 0
  - net.ipv6.conf.all.accept_ra:
      description: >-
        IPv6 Router Advertisements is causing issues on Kimsufi server.
        See https://docs.ovh.com/fr/dedicated/network-ipv6/.
      value: 0

firewalld__sources:
  - { zone: 'trusted', source: '{{ my_home_ipv4 }}', permanent: true, state: 'enabled', immediate: true }
  - { zone: 'trusted', source: '{{ my_home_ipv6 }}', permanent: true, state: 'enabled', immediate: true }

firewalld__services:
  - { zone: 'trusted', service: 'ssh', permanent: true, state: 'enabled', immediate: true }
  - { zone: 'public', service: 'http', permanent: true, state: 'enabled', immediate: true }
  - { zone: 'public', service: 'https', permanent: true, state: 'enabled', immediate: true }
  - { zone: 'public', service: 'dhcpv6-client', permanent: true, state: 'disabled', immediate: true }
  - { zone: 'public', service: 'ssh', permanent: true, state: 'disabled', immediate: true }

certbot__certs:
  - email: 'marc.wrobel@gmail.com'
    webroot: '/var/www/html'
    domains:
      - 'marcwrobel.fr'
      - 'jbanking.marcwrobel.fr'
      - 's1.marcwrobel.fr'

apache_server__state: 'present'
apache_server__bindings:
  - name: 'ipv4'
    ip: '{{ network__ipv4_address }}'
    ports: [80, 443]
  - name: 'ipv6'
    ip: '[{{ network__ipv6_address }}]'
    ports: [80, 443]
apache_server__default_vhost_redirect_target: 'https://www.marcwrobel.fr/'
apache_server__default_vhost_ssl_certificate_file: '/etc/letsencrypt/live/marcwrobel.fr/fullchain.pem'
apache_server__default_vhost_ssl_certificate_key_file: '/etc/letsencrypt/live/marcwrobel.fr/privkey.pem'

postfix_satellite__state: 'present'
postfix_satellite__relay_host: '{{ my_relay_host }}'
postfix_satellite__relay_login: '{{ my_relay_login }}'
postfix_satellite__relay_password: '{{ my_relay_password }}'
