---

kimsufi_network__interface: 'eno0'
kimsufi_network__ipv4_address: '5.196.89.31'
kimsufi_network__ipv4_gateway: '5.196.95.254'
kimsufi_network__ipv6_address: '2001:41d0:a:fc1f::1'
kimsufi_network__ipv6_gateway: '2001:41d0:a:fcff:ff:ff:ff:ff'
