---
- name: Checkout repository
  ansible.builtin.git:
    repo: '{{ dotfiles__repository }}'
    dest: '{{ ansible_env.HOME }}/{{ dotfiles__repository_path }}'
    single_branch: true
    version: '{{ dotfiles__repository_version }}'
    force: true

- name: Install dotfiles
  ansible.builtin.script: '{{ ansible_env.HOME }}/{{ dotfiles__repository_path }}/install'
  check_mode: false
