galaxy_info:
  author: 'Marc Wrobel'
  description: 'Install postfix as a satellite'
  license: 'MIT'
  min_ansible_version: '6.0.0'
  platforms:
    - name: 'Debian'
      versions:
        - 'bullseye'
  galaxy_tags: ['linux', 'debian', 'postfix', 'smtp']
dependencies: []
