---

- name: Install packages for {{ item.namespace }}
  ansible.builtin.package:
    name: "{{ local_facts__script.dependencies }}"
    state: 'present'
  when: '(local_facts__script.dependencies is defined) and (local_facts__script.dependencies | length > 0)'
  register: 'local_facts__install_deps'
  become: true

- name: Install {{ item.namespace }}
  ansible.builtin.template:
    src: 'script.j2'
    dest: '/etc/ansible/facts.d/{{ local_facts__script.namespace }}.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: 'local_facts__install'
  become: true

# changed_when has been forced because this module never returns changes. It do not know if it's a
# bug because fact are actually reloaded, but it feels more natural that way.
- name: Reload facts # noqa no-handler we want it to run now, not at the end of the play
  ansible.builtin.setup:
    gather_subset: 'local'
  when: '(local_facts__install_deps is changed) or (local_facts__install is changed)'
  changed_when: '(local_facts__install_deps is changed) or (local_facts__install is changed)'
