---

- name: 'Ensure sudoers has expect characteristics'
  include_role:
    name: 'marcwrobel.assertions.assert_that_path'
  vars:
    path: '/etc/sudoers'
    has_type: 'file'
    has_mode: '0440'
    has_owner: 'root'
    has_group: 'root'

- name: 'Ensure sudoers is managed by Ansible'
  include_role:
    name: 'marcwrobel.assertions.assert_that_file'
  vars:
    path: '/etc/sudoers'
    has_content_matching: '^#.+Ansible managed'
