---
- name: 'Get /etc/sudoers file status'
  stat:
    path: '/etc/sudoers'
  register: 'sudoers'
- name: 'Ensure /etc/sudoers status is correct'
  assert:
    that:
      - 'sudoers.stat.exists'
      - 'sudoers.stat.mode == "0440"'
      - 'sudoers.stat.uid == 0'
      - 'sudoers.stat.gid == 0'
    fail_msg: '{{ sudoers.stat | to_json }}'

- name: 'Check if Ansible string is absent from /etc/sudoers'
  lineinfile:
    path: '/etc/sudoers'
    regexp: '^#.+Ansible managed'
    state: 'absent'
  check_mode: true
  changed_when: false
  register: 'ansible_managed_line'
- name: 'Ensure /etc/sudoers has been templated by ansible'
  assert:
    that: 'ansible_managed_line.found == 1'
    fail_msg: '/etc/sudoers does not seem to be from a templated Ansible file : {{ ansible_managed_line | to_json }}'
