---

- name: 'Ensure motd file has expected characteristics'
  include_role:
    name: 'marcwrobel.assertions.assert_that_file'
  vars:
    with_path: '/etc/motd'
    has_mode: '0644'
    has_owner: 'root'
    has_group: 'root'
    has_content_matching: '^Warning'
