---

- name: 'Ensure sudoers has expect characteristics'
  include_role:
    name: 'marcwrobel.assertions.assert_that_file'
  vars:
    with_path: '/etc/sudoers'
    has_mode: '0440'
    has_owner: 'root'
    has_group: 'root'
    has_content_matching: '^#.+Ansible managed'
