---
name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '6 6 * * 6'

jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the codebase'
        uses: 'actions/checkout@v3'

      - name: 'Set up Python 3'
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: 'Install dependencies'
        run: |
          pip3 install pipenv
          pipenv install

      - name: 'Run Ansible-lint'
        run: |
          pipenv run ansible-lint --version
          pipenv run ansible-lint
